=== leiti20/app-Rest/src/main/resources/xml/sepa26.tp1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://univ.fr/sepa"
    xmlns="http://univ.fr/sepa"
    elementFormDefault="qualified">

    <xs:simpleType name="Max35Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
            <xs:pattern value="[^/]+(/[^/]+)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Max15NumericText">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,15}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Amount">
        <xs:simpleContent>
            <xs:extension base="DecimalNumber">
                <xs:attribute name="Ccy" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="DecimalNumber">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="18"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IBANType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="BICType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3})?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="CmpsdIdt">
        <xs:sequence>
            <xs:element name="Id">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="IBAN" type="IBANType"/>
                        <xs:element name="PrvtId">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Othr">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Id" type="Max35Text"/>
                                                <xs:element name="SchmeNm">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="Prtry" type="xs:string" fixed="SEPA"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CmpsdAgt">
        <xs:sequence>
            <xs:element name="FinInstnId">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="BIC" type="BICType"/>
                        <xs:element name="Othr">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Id" type="Max35Text"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Document">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CstmrDrctDbtInitn">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="GrpHdr">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MsgId" type="Max35Text"/>
                                        <xs:element name="CreDtTm" type="xs:dateTime"/>
                                        <xs:element name="NbOfTxs" type="Max15NumericText"/>
                                        <xs:element name="CtrlSum" type="DecimalNumber"/>
                                        <xs:element name="InitgPty">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Nm" type="Max35Text"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="PmtInf" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="PmtInfId" type="Max35Text"/>
                                        <xs:element name="PmtTpInf">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="SvcLvl"><xs:complexType><xs:sequence><xs:element name="Cd" type="xs:string" fixed="SEPA"/></xs:sequence></xs:complexType></xs:element>
                                                    <xs:element name="LclInstrm"><xs:complexType><xs:sequence><xs:element name="Cd" type="xs:string"/></xs:sequence></xs:complexType></xs:element>
                                                    <xs:element name="SeqTp" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="ReqdColltnDt" type="xs:date"/>
                                        <xs:element name="Cdtr">
                                            <xs:complexType><xs:sequence><xs:element name="Nm" type="Max35Text"/></xs:sequence></xs:complexType>
                                        </xs:element>
                                        <xs:element name="CdtrAcct" type="CmpsdIdt"/>
                                        <xs:element name="CdtrAgt" type="CmpsdAgt"/>
                                        <xs:element name="CdtrSchmeId" minOccurs="0" type="CmpsdIdt"/>
                                        
                                        <xs:element name="DrctDbtTxInf" maxOccurs="10">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="PmtId" type="Max35Text"/>
                                                    <xs:element name="InstdAmt" type="Amount"/>
                                                    <xs:element name="DrctDbtTx">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="MndtRltdInf">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="MndtId" type="Max35Text"/>
                                                                            <xs:element name="DtOfSgntr" type="xs:date"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="DbtrAgt" type="CmpsdAgt"/>
                                                    <xs:element name="Dbtr">
                                                        <xs:complexType><xs:sequence><xs:element name="Nm" type="Max35Text"/></xs:sequence></xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="DbtrAcct" type="CmpsdIdt"/>
                                                    <xs:element name="RmtInf" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== leiti20/app-Rest/src/main/resources/xml/sepa_conforme.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="http://univ.fr/sepa"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://univ.fr/sepa sepa26.tp1.xsd">
    <CstmrDrctDbtInitn>
        <GrpHdr>
            <MsgId>MSG-2026-001</MsgId>
            <CreDtTm>2026-04-27T10:00:00</CreDtTm>
            <NbOfTxs>1</NbOfTxs>
            <CtrlSum>1250.50</CtrlSum>
            <InitgPty>
                <Nm>ENTREPRISE ALPHA</Nm>
            </InitgPty>
        </GrpHdr>
        <PmtInf>
            <PmtInfId>PMT-001</PmtInfId>
            <PmtTpInf>
                <SvcLvl><Cd>SEPA</Cd></SvcLvl>
                <LclInstrm><Cd>CORE</Cd></LclInstrm>
                <SeqTp>FRST</SeqTp>
            </PmtTpInf>
            <ReqdColltnDt>2026-05-15</ReqdColltnDt>
            <Cdtr>
                <Nm>ENTREPRISE ALPHA</Nm>
            </Cdtr>
            <CdtrAcct>
                <Id>
                    <IBAN>FR7630006000010123456789012</IBAN>
                </Id>
            </CdtrAcct>
            <CdtrAgt>
                <FinInstnId>
                    <BIC>BNPAFRPPXXX</BIC>
                </FinInstnId>
            </CdtrAgt>
            <DrctDbtTxInf>
                <PmtId>TX-001</PmtId>
                <InstdAmt Ccy="EUR">1250.50</InstdAmt>
                <DrctDbtTx>
                    <MndtRltdInf>
                        <MndtId>MANDAT-001</MndtId>
                        <DtOfSgntr>2026-01-01</DtOfSgntr>
                    </MndtRltdInf>
                </DrctDbtTx>
                <DbtrAgt>
                    <FinInstnId>
                        <BIC>SOGEFRPPXXX</BIC>
                    </FinInstnId>
                </DbtrAgt>
                <Dbtr>
                    <Nm>JEAN DUPONT</Nm>
                </Dbtr>
                <DbtrAcct>
                    <Id>
                        <IBAN>FR7612345678901234567890123</IBAN>
                    </Id>
                </DbtrAcct>
                <RmtInf>PAIEMENT FACTURE 123</RmtInf>
            </DrctDbtTxInf>
        </PmtInf>
    </CstmrDrctDbtInitn>
</Document>
